name: CI

on:
  push:
  pull_request:

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Install deps
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Code style (dry-run)
        run: composer cs:check

      - name: Static analysis
        run: composer stan

      - name: Tests
        run: composer test
